# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: 
    - main
    - develop
    - feature/test_bootstrap_ci
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

# The following command allows to connect to the ci-container via ssh
# very useful for debugging
# source: https://github.com/marketplace/actions/debugging-with-tmate

#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3

    - name: Install pip
      run: |
        python -m pip install --upgrade pip

    - name: Install pyirk
      run: |
        git clone https://github.com/ackrep-org/pyirk-core.git
        cd pyirk-core
        git checkout ut__ocse__main
        pip install .

    - name: Installing requirements
      run: |
        # install this package
        pwd
        pip install -r requirements.txt

    - name: run all tests
      run: |
        python -m unittest
